services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=production
      - VITE_BASE_URL=https://data.origamid.dev/vendas
    volumes:
      - .:/app
    command: npm run start
    working_dir: /app
    restart: unless-stopped
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
